#!/usr/bin/env sh
set -eu

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

python3 -m pip install -r "$script_dir/requirements.txt"

if command -v tectonic >/dev/null 2>&1; then
  exit 0
fi

cd "$(mktemp -d)"
curl -fsSL https://drop-sh.fullyjustified.net | sh
mv tectonic ~/.local/bin/tectonic
chmod +x ~/.local/bin/tectonic
